#
# Makefile
#
# Computer Science 50
# Problem Set 4
#
copy: copy.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o copy copy.c -lcs50 -lm
	
whodunit: whodunit.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o whodunit whodunit.c -lcs50 -lm
	
resize: resize.c
	clang -ggdb3 -O0 -std=c11 -Wall -Werror -o resize resize.c -lcs50 -lm
	